import { Script } from "./script"
import { Anagram } from "./anagram"
import { Hangman } from "./hangman"
import { Pig } from "./pig"
import { Ox } from "./ox"
import { Flash } from "./flash"
import { Mine } from "./mine"
